version: "3.8"

services:
  alb_demo:
    image: alb_demo
    container_name: $USER-alb_demo
    user: docker
    working_dir: /alb-demo
    command: [ "jupyter", "notebook", "--no-browser", "--ip", "0.0.0.0", "--port", "8000" ]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
        BASE_IMAGE: $BASE_IMAGE
        PYTHON_VERSION: $PYTHON_VERSION
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./images
        target: /alb-demo/images
    deploy:
      resources:
        limits:
          memory: 64g
    cpuset: "0-15"
    security_opt:
      - label:disable
    shm_size: 8g
